---
# defaults file for oc
model_list:
  - system
  - interfaces
  - 'network-instance'
oc_model_map:
  system: 'openconfig-system:system'
  interfaces: 'openconfig-interfaces:interfaces'
  network-instance: 'openconfig-network-instance:network-instances'

oc_group_list: "{{ regions }}"
oc_file_patterns:
  - 'oc-*.yml'
oc_data_root: "{{ lookup('env', 'PWD') }}/mdd-data"
