---
#
# Iterate through each of the schema groups and run the schema(s) if the tags match
#
- name: Run Validation Groups
  include_tasks: validate_schema_group.yml
  with_items: "{{ schema_group_list }}"
  when: "'all' in schema_group_table[schema_group_name].tags | default(['all']) or schema_group_table[schema_group_name].tags | default([]) | intersect(tags | default([])) | length"
  loop_control:
    loop_var: 'schema_group_name'
  vars:
    schema_path: "{{ schema_group_table[schema_group_name].path }}"
    