- name: Find all schemas
  find:
    paths: "{{ schema_root }}/{{ schema_path }}"
    recurse: yes
    patterns: '*.yml,*.yaml,*.json'
  register: find_results

- name: Validate data
  datavalidation:
    data: "{{ mdd_data }}"
    schema_file: "{{ schema_file }}"
  register: validation_output
  loop: "{{ find_results.files | map(attribute='path') | list }}"
  loop_control:
    loop_var: schema_file
  ignore_errors: yes

- set_fact:
    validation_failures: '{{ validation_output.results | selectattr("failed", "equalto", True) | map(attribute="schema_name") | list | default([]) }}'

# - debug:
#     msg: "Failed schemas: {{ validation_failures | join(',') }}"
#   failed_when: validation_failures | length
#   when: validation_failures | length