- name: Check if device is in sync
  cisco.nso.nso_action:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    path: '/ncs:devices/device{"{{ device_name | default(inventory_hostname) }}"}/check-sync'
    input: {}
  register: action_result
  changed_when: False
  failed_when: "(action_result.output is defined and 'out-of-sync' in action_result.output.result) or (action_result.msg is defined and 'error' in action_result.msg)"