- name: Check if device is in sync
  cisco.nso.nso_action:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    path: '/ncs:devices/device{"{{ device_name | default(inventory_hostname) }}"}/check-sync'
    input: {}
  register: check_result
  changed_when: False
  failed_when: "check_result.msg is defined and 'error' in check_result.msg"

- block:
  - name: Compare Config
    cisco.nso.nso_action:
      url: "{{ nso_url }}"
      username: "{{ nso_username }}"
      password: "{{ nso_password }}"
      path: '/ncs:devices/device{"{{ device_name | default(inventory_hostname) }}"}/compare-config'
      input: {}
    register: compare_result
    changed_when: False

  - debug:
      var: compare_result.output.diff
    failed_when: True

  when: "(check_result.output is defined and 'out-of-sync' in check_result.output.result)"