- name: Get NSO to generate native config
  cisco.nso.nso_config:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    data:
      tailf-ncs:devices:
        device:
        - name: "{{ inventory_hostname }}"
          config:
            __state: absent
    commit_flags:
      - 'commit'
      - 'dry-run outformat native'
      - 'reverse'
  register: nso_config_results

- debug:
    var: nso_config_results