- name: Create host in NSO
  cisco.nso.nso_config:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    data:
      tailf-ncs:devices:
        device:
        - address: "{{ nso_device_ipv4 }}"
          description: "{{ nso_device_description | default(omit) }}"
          name: "{{ nso_device_name | default(inventory_hostname) }}"
          authgroup: "{{ nso_auth_group | default('default') }}"
          device-type:
            cli:
              ned-id: "{{ device_ned | default(nso_default_ned) }}"
          port: "22"
          state:
            admin-state: "{{ nso_device_admin_state | default('unlocked') }}"

- name: Load native config for device
  cisco.nso.nso_action:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    path: '/ncs:devices/ncs:device{"{{ nso_device_name }}"}/load-native-config'
    input:
      data: "{{ nso_device_config }}"
      verbose: true
      mode: "merge"
  register: load_result
  ignore_errors: true