#
# If nso_host was not set in inventory, see if it is an environment variable.
#
- set_fact:
    nso_host: "{{ lookup('env', 'NSO_HOST') | default('') }}"
  when: nso_host is not defined or not nso_host

#
# If not set as an environment variable, then see if we can figure it out from
# the inventory
#
- set_fact:
    nso_host: "{{ hostvars[nso_hostname].ansible_host }}"
  when: "not nso_host and nso_host_group in groups"
  vars:
    nso_hostname: "{{ groups[nso_host_group] | first }}"

- set_fact:
    nso_username: "{{ lookup('env', 'NSO_USERNAME') | default ('ubuntu') }}"
    nso_password: "{{ lookup('env', 'NSO_PASSWORD') | default ('admin') }}"
  when: nso_username is not defined or not nso_username

- block:
  - name: Make sure that we have an NSO host to talk to
    assert:
      that:
        - nso_host is defined
        - nso_host
      fail_msg: "Cannot find an NSO host to use"
      success_msg: "Using NSO host: {{ nso_host }}"

  - set_fact:
      nso_available: yes
  when: nso_required | default('yes') | bool
