- name: Sync NSO device
  cisco.nso.nso_action:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    path: '/ncs:devices/device{"{{ device_name | default(inventory_hostname) }}"}/sync-from'
    input: {}
  register: nso_results
  failed_when: "nso_results.output.result == 'false'"
  changed_when: "nso_results.output.result == 'changed'"