- name: Update OC Service
  cisco.nso.nso_config:
    url: "{{ nso_url }}"
    username: "{{ nso_username }}"
    password: "{{ nso_password }}"
    commit_flags: "{{ 'dry-run=native' if dry_run | bool else [] }}"
    load: yes
    load_mode: replace
    load_path: '/ncs:devices/device{{ "{" }}{{ inventory_hostname }}{{ "}" }}/mdd:openconfig'
    data:
      "{{ mdd_data }}"
  register: nso_config_result

# - debug:
#     var: nso_config_result

- set_fact:
    rollback_id: "{{ nso_config_result | json_query(query) }}"
  vars:
    query: 'commit_result[0]."rollback-id".fixed'

- debug:
    msg: "Rollback Id: {{ rollback_id }}"
  when: rollback_id is defined and rollback_id
      