    - name: Get VLANs
      include_role:
        name: ciscops.mdd.nso
        tasks_from: get_vlan

    - name: Update VLANs
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: add_vlan
      vars:
        netbox_vlan_name: "{{ item.name }}"
        netbox_vlan_id: "{{ item.id }}"
      when: item.name is defined
      loop: "{{ nso_vlan_list | default ([]) }}"