- name: Get Routing Information
  include_role:
    name: ciscops.mdd.nso
    tasks_from: get_router

- name: Create host inventory directory
  ansible.builtin.file:
    path: "{{ mdd_device_dir }}"
    state: directory

- name: Write OC Host Data to inventory file 
  copy:
    content: "{{ oc_routing_data | to_nice_yaml(indent=2) }}"
    dest: "{{ mdd_device_dir }}/oc-routing.yml"
  delegate_to: localhost
  when: nso_routing_list is defined and nso_routing_list
  vars:
    oc_routing_data: "{{ lookup('template', 'oc-router.yml.j2') | from_yaml }}"