    - name: Get VRFs
      include_role:
        name: ciscops.mdd.nso
        tasks_from: get_vrf

    - name: Update VRFs
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: add_vrf
      vars:
        netbox_vrf_name: "{{ item.name }}"
        netbox_vrf_rd: "{{ item.rd | default (omit) }}"
      loop: "{{ nso_vrf_list | default ([]) }}"