  - name: Update System Information
    uri:
      url: "{{ nso_rest_url }}/restconf/data/tailf-ncs:devices/device={{ inventory_hostname }}/mdd:openconfig{{ '?dry-run=native' if dry_run | bool else '' }}" 
      url_username: "{{ nso_username }}"
      url_password: "{{ nso_password }}"
      force_basic_auth: yes
      validate_certs: no
      status_code: [200, 201, 204]
      method: PUT
      headers: "{
        'Content-Type': 'application/yang-data+json',
        'Accept': 'application/yang-data+json'}"
      body_format: json
      body: 
        "{{ mdd_data }}"
      return_content: yes
      timeout: 600
    register: nso_update_result

  # - debug:
  #     var: nso_update_result.json
  #   when: "'json' in nso_update_result and dry_run | bool"
  #   changed_when: nso_update_result.json["dry-run-result"].native

# - name: Update OC Service
#   cisco.nso.nso_config:
#     url: "{{ nso_url }}"
#     username: "{{ nso_username }}"
#     password: "{{ nso_password }}"
#     # commit_flags:
#     #   - 'dry-run=cli'
#     # state: set
#     data:
#         tailf-ncs:devices:
#           device:
#           - name: "{{ inventory_hostname }}"
#             mdd:openconfig: "{{ mdd_data['mdd:openconfig'] }}"
#             __state: set
#   register: config_result

# - debug:
#     var: config_result