    - name: Get Interfaces
      include_role:
        name: ciscops.mdd.nso
        tasks_from: get_interface

    - name: Update Interfaces
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: nso_interface_list
      vars:
        nso_interface_type: "{{ nso_interface_type_item.key }}"
        nso_interface_type_list: "{{ nso_interface_type_item.value }}"
      with_dict: "{{ nso_interface_dict | default({}) }}"
      loop_control:
        loop_var: nso_interface_type_item