---
nso_host_group: 'nso'
nso_port: "{{ lookup('env', 'NSO_PORT') | default('8080', true) }}"
nso_protocol: "{{ lookup('env', 'NSO_PROTOCOL') | default('http', true) }}"
nso_url: "{{ nso_protocol }}://{{ nso_host }}:{{ nso_port }}/jsonrpc"
nso_rest_url: "{{ nso_protocol }}://{{ nso_host }}:{{ nso_port }}"
nso_package_src: "{{ lookup('env', 'PWD') }}/packages"
nso_installer_name: "nso-5.5.3.linux.x86_64.signed.bin"
nso_install_dir: /opt/ncs/current
nso_run_dir: /var/opt/ncs
nso_etc_dir: /etc/ncs
nso_tmp_dir: /tmp/nso
nso_upload_dir: /tmp/nso
nso_java_opts: "-Xmx2G -Xms1G"
# Default username/password for the NSO host
# admin_user: ubuntu
# admin_password: admin
# ansible_user: "{{ admin_user }}"
# ansible_password: "{{ admin_password }}"
nso_username: "{{ lookup('env', 'NSO_USERNAME') | default ('ubuntu', true) }}"
nso_password: "{{ lookup('env', 'NSO_PASSWORD') | default ('admin', true) }}"
# The auth groups to add.  Override in the inventory
nso_auth_groups:
  default:
    remote_name: "admin"
    remote_password: "admin"
nso_default_ned: cisco-ios-cli-6.77
nso_ned_dict:
  ios: "cisco-ios-cli-6.77"
nso_package_repos:
  - name: mdd
    repo: https://github.com/model-driven-devops/nso-oc-services.git
    service_list:
      - mdd
