---
# defaults file location for data_validation
schema_root: "{{ lookup('env', 'PWD') }}/schemas"
# The list of groups to append to schema_dir in which to search for files.
# Note: role_dir/files/schemas is appended to the end as a default location.
schema_group_dirs: "{{ group_names }}"
#
# The list of schmema groups to validate
#
schema_group_list:
  - stig
schema_group_table:
  stig:
    path: 'stig/CISC-ND_IOSXE.schema'
    tags:
      - all