- name: Run command {{ check_table[check_name].command }}
  include_role:
    name: ciscops.mdd.check
    tasks_from: "{{ check_table[check_name].method }}"
  vars:
    check_command: "{{ check_table[check_name].command }}"

# - debug:
#     var: parsed_output

- block:
    - name: Validate data against schema {{ schema_file }}
      ciscops.mdd.data_validation:
        data: "{{ parsed_output }}"
        schema: "{{ lookup('file', lookup('first_found', params)) | from_yaml }}"
      register: validation_output
      vars:
        params:
          files:
            - '{{ check_table[check_name].schema }}'
          paths: "{{ schema_path_list }}"
  rescue:
    - set_fact:
        failed_checks: "{{ (failed_checks | default([])) + [check_name] }}"