- name: Run command {{ check_item.command }}
  include_role:
    name: ciscops.mdd.check
    tasks_from: "{{ check_item.method }}"
  vars:
    check_command: "{{ check_item.command }}"

- block:
    - name: Check data against the schema
      ciscops.mdd.data_validation:
        data: "{{ parsed_output }}"
        schema: "{{ lookup('template', schema) | from_yaml }}"
      register: validation_output
      vars:
        check_vars: "{{ check_item.check_vars }}"
        schema: "{{ schema_root }}/{{ check_item.schema }}"
  rescue:
    - set_fact:
        failed_checks: "{{ (failed_checks | default([])) + [check_item.name] }}"