---
#
# Create a heirarchical directory derived from the groups/regions this device
# is a part of.  This can be set via the oc_dir_items variable with a default
# in the role.
#
- include_role:
    name: ciscops.mdd.common
    tasks_from: files_in_path
  vars:
    mdd_file_patterns: "{{ mdd_oc_patterns }}"

#
# Merge in the data from the file if the tags match with the host (or are not specified)
#
- name: Combine the OC Data
  set_fact:
    mdd_data: "{{ mdd_data | default({}) | ciscops.mdd.oc_combine(mdd_file.mdd_data | default({}), recursive=True) }}"
  loop: "{{ mdd_file_list }}"
  when: ('all' in mdd_file.mdd_tags | default(['all'])) or (mdd_file.mdd_tags | intersect(tags | default([])))
  vars:
    mdd_file: "{{ lookup('template', item ) | from_yaml }}"

- include_tasks: netbox.yml