- hosts: network
  connection: local
  gather_facts: no
  roles:
    - role: ciscops.mdd.nso
      vars:
        nso_required: no
  tasks:
    - name: Run Checks
      include_role:
        name: ciscops.mdd.check

    - debug:
        var: failed_checks
      when: failed_checks is defined and failed_checks
      failed_when: failed_checks is defined and failed_checks