- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_host: "{{ lookup('env', 'NETBOX_HOST') | default (hostvars['netbox'].ansible_host) }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    netbox_url: "{{ lookup('env', 'NETBOX_URL') }}"
  tasks:
    - cisco.cml.cml_lab_facts:
      register: cml_lab_results

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: netbox_inventory

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: netbox_mgmt
      when: item.value.ansible_host_interface is defined and item.key in netbox_host_list
      with_dict: "{{ cml_lab_results.cml_facts.nodes }}"
      vars:
        device_name: "{{ item.key }}"
        interface_name: "{{ item.value.ansible_host_interface }}"
        ip_address: "{{ item.value.ansible_host }}"