---
- name: elevate configs
  hosts: localhost
  gather_facts: false
  roles:
    - ciscops.mdd.data

  vars:
    temp_dir: "{{ mdd_data_parent }}/temp_dir"

  vars_prompt:

    - name: file_level_input
      prompt: What file level would you like to elevate at?
      private: false

    - name: is_test_run_input
      prompt: Would you like to see the results before committing? (yes/no)?
      private: false

  tasks:

    - name: Convert is_test_run to boolean
      set_fact:
        is_test_run: "{{ is_test_run_input | bool }}"
    - name: Convert file_level to boolean
      set_fact:
        file_level: "{{ file_level_input | int }}"

    - name: elevate
      elevate_configs: # you will never know how this actually works lol ;)
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: "{{ is_test_run }}"
        temp_dir: "{{ temp_dir }}"
      register: elevate_result

    - debug:
        var: elevate_result.debug

    - pause:
        prompt: "Is this result okay? (yes/no)"
        echo: yes
      register: result
      when: is_test_run == true
    - set_fact:
        is_ok_continue: false
    - set_fact:
        is_ok_continue: "{{ result.user_input | bool }}"
      when: is_test_run == true

    - name: Delete temp directory if present
      file:
        path: "{{ temp_dir }}/"
        state: absent
      when: is_ok_continue == false

    - name: elevate
      elevate_configs: # you will never know how this actually works lol ;)
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: false
        temp_dir: "{{ temp_dir }}"
      register: result
      when: is_ok_continue == true

