---
- name: elevate configs
  hosts: localhost
  gather_facts: false
  roles:
    - ciscops.mdd.data

  vars:
    temp_dir: "{{ mdd_data_parent }}/temp_dir"
    file_level: "{{ level | default(-1) }}"
    is_test_run: "{{ test | default(false) }}"

  tasks:

    # - pause:
    #     prompt: "Would you like to see the results before committing? (yes/no)"
    #     echo: yes
    #   register: is_test_run_input
    #   until: is_test_run_input.user_input.lower() in ['yes', 'no', 'y', 'n']
    #   retries: 5
    #   delay: 1
    # - set_fact:
    #     is_test_run: false
    #   when: is_test_run_input.user_input.lower() in ['no', 'n']
    # - set_fact:
    #     is_test_run: true
    #   when: is_test_run_input.user_input.lower() in ['yes', 'y']
    - debug:
        var: file_level

    - name: elevate
      elevate_configs: # you will never know how this actually works lol ;)
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: "{{ is_test_run }}"
        temp_dir: "{{ temp_dir }}"
      register: elevate_result

    - debug:
        var: elevate_result.debug

    - pause:
        prompt: "Is this result okay? (yes/no)"
        echo: yes
      register: result
      until: result.user_input.lower() in ['yes', 'no', 'y', 'n']
      retries: 5
      delay: 1
      when: is_test_run == true

    - set_fact:
        is_ok_continue: false
    - set_fact:
        is_ok_continue: true
      when: is_test_run == true and result.user_input.lower() in ['yes', 'y']

    - name: Delete temp directory if present
      file:
        path: "{{ temp_dir }}/"
        state: absent
      when: is_ok_continue == false

    - name: elevate
      elevate_configs: # you will never know how this actually works lol ;)
        mdd_data_dir: "{{ mdd_data_root }}"
        mdd_data_patterns: "{{ mdd_data_patterns }}"
        file_level: "{{ file_level }}"
        is_test_run: false
        temp_dir: "{{ temp_dir }}"
      register: result
      when: is_ok_continue == true

