- name: Add Hosts to NSO
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  tasks:
    - name: Get OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: get_oc_data

    - name: Update Local Context
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_local_context
      vars:
        netbox_device_local_context: "{{ nso_device_oc_data }}"