- name: Push OC Interfaces to NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
    - role: ciscops.mdd.netbox
      vars:
        netbox_required: no
    - ciscops.mdd.oc
  vars:
    dry_run: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync

    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_oc

    - include_role:
        name: ciscops.mdd.netbox
        tasks_from: update_rollback_list
      when: rollback_id is defined and rollback_id and netbox_available | default(no)

- name: Run update_report
  hosts: all
  connection: local
  gather_facts: no
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool