- hosts: nso
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  tasks:
    - name: Add NSO Auth Groups
      include_role:
        name: ciscops.mdd.nso
        tasks_from: add_auth_groups
