- name: Add Hosts to NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync