- name: Add Hosts to NSO
  hosts: all
  connection: local
  gather_facts: no
  vars:
    netbox_host: "{{ lookup('env', 'NETBOX_HOST') | default (hostvars['netbox'].ansible_host) }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
    nso_host: "{{ lookup('env', 'NSO_HOST') | default(omit) }}"
  tasks:
    - debug:
        var: version

    - name: Update Device
      include_role:
        name: ciscops.mdd.netbox
        tasks_from: add_device
      vars:
        netbox_device_name: "{{ inventory_hostname }}"
        netbox_device_type: "{{ version.model | default('switch') }}"
        netbox_device_serial: "{{ version.serial | default(omit) }}"
        netbox_device_platform: "{{ version.name | default(omit) }}"