- name: Update YAML from NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    host_data_directory: "{{ lookup('env', 'PWD') }}/mdd-data/{{ regions | reverse | join('/') }}/{{ inventory_hostname }}"
  tasks:
    - name: Update Routing
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_yaml_router
