- hosts: network
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  run_once: true
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: rollback

    - debug:
        var: nso_rollback_facts
