- hosts: localhost
  gather_facts: no
  vars:
    nso_host: "{{ lookup('env', 'NSO_HOST') | default (hostvars['nso'].ansible_host) }}"
    config_dir: "{{ lookup('env', 'PWD') }}/configs"
  tasks:
    - name: Find config files in directory
      find:
        paths: "{{ config_dir }}"
        patterns: "^.*\\.(txt|cfg)$"
        use_regex: yes
      register: config_files

    # - debug:
    #     msg: "{{ device_name }}, {{ device_config_file }}"
    #   loop: "{{ config_files.files }}"
    #   vars:
    #     device_name: "{{ item.path }}"
    #     device_config_file: "{{ item.path | regex_search('/([^\\/\\.]+)\\.(txt|cfg)$', '\\1') | first }}"

    - name: Load Config
      include_role:
        name: ciscops.mdd.nso
        tasks_from: load_config
      vars:
        nso_device_ipv4: 127.0.0.1
        nso_device_name: "{{ item.path | regex_search('/([^\\/\\.]+)\\.(txt|cfg)$', '\\1') | first }}"
        nso_device_config: "{{ lookup('file', item.path) }}"
        nso_device_admin_state: "southbound-locked"
        nso_device_description: "Loaded from device config"
      loop: "{{ config_files.files }}"
      