- name: Push OC Interfaces to NSO
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    dry_run: true
    models: all
  tasks:
    - include_role:
        name: ciscops.mdd.nso
        tasks_from: check_sync
      when: not dry_run | bool

    - name: Get OC Data
      include_role:
        name: ciscops.mdd.oc
        tasks_from: "{{ models }}"

    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_oc

    - block:
      - name: Get OC All Data
        include_role:
          name: ciscops.mdd.nso
          tasks_from: get_oc_data

      - name: Update Local Context
        include_role:
          name: ciscops.mdd.netbox
          tasks_from: update_local_context
        vars:
          netbox_device_local_context: "{{ nso_device_oc_data }}"
      when: not dry_run | bool

- name: Run update_report
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    dry_run: true
  tasks:
    - name: Update OC Data
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_report
      run_once: true
      when: dry_run | bool