- name: Add Hosts to NSO
  hosts: network
  connection: local
  gather_facts: no
  serial: 1
  roles:
    - ciscops.mdd.netbox
    - ciscops.mdd.nso
  tasks:
    # - include_role:
    #     name: ciscops.mdd.nso
    #     tasks_from: get_device_list

    - name: Update VLANs
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_netbox_vlans

    # - name: Update VRFs
    #   include_role:
    #     name: ciscops.mdd.nso
    #     tasks_from: update_netbox_vrfs

    - name: Update Interfaces
      include_role:
        name: ciscops.mdd.nso
        tasks_from: update_netbox_interfaces