- name: Add Hosts to NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  tasks:
    - block:
      - name: Add Host to NSO
        include_role:
          name: ciscops.mdd.nso
          tasks_from: add_host

      - name: Sync Host
        include_role:
          name: ciscops.mdd.nso
          tasks_from: sync_from
      when: ansible_host is defined