- name: Add Hosts to NSO
  hosts: network
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  tasks:
    - name: Sync Host
      include_role:
        name: ciscops.mdd.nso
        tasks_from: action
      vars:
        nso_action: 'sync-to'
