- hosts: all
  connection: local
  gather_facts: no
  roles:
    - ciscops.mdd.nso
  vars:
    check_list:
      - bgp_neighbors
    schema_dir: "{{ lookup('env', 'PWD') }}/schemas"
  tasks:
    - name: Run Checks
      include_role:
        name: ciscops.mdd.check
        tasks_from: find_schema
