- name: Add Hosts to NSO
  hosts: ios
  connection: local
  gather_facts: no
  vars:
    nso_hostname: "{{ groups.nso_hosts | first }}"
    # nso_host: "{{ lookup('env', 'NSO_HOST') | default(hostvars[nso_hostname].ansible_host) }}"
    nso_host: "{{ hostvars[nso_hostname].ansible_host }}"
  tasks:
    - name: Add Host to NSO
      include_role:
        name: ciscops.devops.nso
        tasks_from: add_host

    - name: Sync Host
      include_role:
        name: ciscops.devops.nso
        tasks_from: sync_host