- hosts: all
  connection: local
  gather_facts: no
  ignore_errors: yes
  roles:
    - ciscops.mdd.oc               # Loads the OC Data
    - ciscops.mdd.data_validation  # Validates the OC Data
    
- name: Run update_report
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: Run Validation Report
      include_role:
        name: ciscops.mdd.data_validation
        tasks_from: validation_report
      run_once: true

    - fail:
        msg: "Failed Validation"
      when: validation_failures is defined and validation_failures
      