- name: Create device type within Netbox with only required information
  netbox.netbox.netbox_device_type:
    netbox_url: "https://{{ netbox_host }}"
    netbox_token: "{{ netbox_token }}"
    data:
      slug: "{{ device_type | lower }}"
      model: "{{ device_type }}"
      manufacturer: "{{ device_manufacturer | default(default_netbox_manufacturer) }}"
    state: present
    validate_certs: false
