- name: Set Defaults
  set_fact:
    interface_untagged_vlan: ''
    interface_tagged_vlans: []
    interface_mode: ''

- name: Create Interface {{ netbox_device_name }}:{{ netbox_device_interface_name }}
  netbox.netbox.netbox_device_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      device: "{{ netbox_device_name }}"
      name: "{{ netbox_device_interface_name }}"
      mgmt_only: yes
      enabled: yes
    state: present
    validate_certs: "{{ netbox_validate_certs }}"
  register: interface_result
  ignore_errors: yes

- name: Add IP address {{ netbox_device_ipv4_address }}
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ netbox_device_ipv4_address }}"
      # vrf: Test
      # description: "{{ interface.description | default(omit) }}"
      assigned_object:
        device: "{{ netbox_device_name }}"
        name: "{{ netbox_device_interface_name }}"
      status: DHCP
    state: present
    validate_certs: "{{ netbox_validate_certs }}"

- name: Set Primary IP4 for {{ netbox_device_name }} to {{ netbox_device_ipv4_address }}
  netbox.netbox.netbox_device:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ netbox_device_name }}"
      primary_ip4: "{{ netbox_device_ipv4_address }}"
    state: present
    validate_certs: "{{ netbox_validate_certs }}"