- name: Create VLAN
  netbox.netbox.netbox_vlan:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    query_params:
      - name
      - vid
      - site
    data:
      name: "{{ vlan.name }}"
      vid: "{{ vlan.id }}"
      site: "{{ netbox_site }}"
    state: present
    validate_certs: "{{ netbox_validate_certs }}"
  ignore_errors: no
